name: virustotal
on: workflow_dispatch
jobs:
  virustotal:
    runs-on: ubuntu-slim
    steps:
      - name: VirusTotal
        uses: cssnr/virustotal-action@v1
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_KEY }}
          release_id: latest
          release_heading: "### ğŸ›¡ï¸ VirusTotal Results"
